event.stopPropagation();
$(document).ready(function(){});
$("#id").click(function(){});
$("#id").bind(type,function(event){});
$("#id").bind(type1:function(){},type2:function(){});
$("#id").hover(function(){},function(){})//mouseenter,mouseleave
$("#id").show();
$("#id").hide();
$("#id").toggle(fun1,fun2,fun3);
$("#id").unbind();
$("#id").one(fun);
$("#id").trigger();
$("#select").change()
$("#id").siblings()//所有兄弟节点，不只是id之后
$(window).resize(fun);
$("#id")
$("#id")
$("#id")
$("#id")
$("#id")
$("#id")
$("#id")