this.toggleClass("classname");
$("#id:even");
$("#id:eq(n)");
$("#id:not()");
$("#id:contians()");
$("#id:has()");
$("#id:empty");
$("#id:parent");
$(".class:hidden");
$(".class:visible");
$(".class[attr!=nn]");//^=;$=;*=;
$("#id:nth-child()");
$("#id:first-child");
$("#id:only-child");
//表单属性选择器
$("#id:enabled");
$("#id:disabled");
$("#id:checked");
$("#id:selected");
//表单选择器
$("#id:input");
$("#id:text");
$("#id:password");
$("#id:radio");
$("#id:checkbox");
$("#id:submit");
$("#id:image");
$("#id:reset");
$("#id:button");
$("#id:file");
$("#id:reset");

